apiVersion: v1
kind: ConfigMap
metadata:
  name: hrms-backend-config
  namespace: hrms-lite
data:
  APP_NAME: HRMS Lite
  APP_ENV: production
  APP_DEBUG: "false"
  API_V1_PREFIX: /api
  CORS_ALLOWED_ORIGINS: '["http://localhost:5173","http://127.0.0.1:5173"]'
  DATABASE_URL: postgresql+psycopg://postgres:postgres@hrms-postgres:5432/hrms_lite
  RABBITMQ_URL: amqp://guest:guest@hrms-rabbitmq:5672/
  RABBITMQ_EXCHANGE: hrms.events
  RABBITMQ_LISTENER_QUEUE: hrms.activity.listener
  RABBITMQ_INTERNAL_TOPIC: internal.#
  RABBITMQ_ACTIVITY_TOPIC: activity.#
  RABBITMQ_RECONNECT_SECONDS: "3"
  EVENT_PUBLISH_ENABLED: "true"
  EVENT_LISTENER_ENABLED: "true"
