apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrms-frontend
  namespace: hrms-lite
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hrms-frontend
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hrms-frontend
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: interview-asignments-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
          readinessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 500m
              memory: 384Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hrms-frontend
  namespace: hrms-lite
spec:
  selector:
    app.kubernetes.io/name: hrms-frontend
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 5173
      targetPort: 5173
