apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hrms-lite
resources:
  - namespace.yaml
  - backend-configmap.yaml
  - secrets.template.yaml
  - rabbitmq.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - nginx-configmap.yaml
  - nginx.yaml
  - hpa.yaml
