apiVersion: v1
kind: Secret
metadata:
  name: hrms-secrets
  namespace: hrms-lite
type: Opaque
stringData:
  POSTGRES_DB: hrms_lite
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  SUPERADMIN_KEY: kjgdfhkgjhd-fjgkehslgjg
